drink_profiles = {
    "green_tea": {
        "energy": 0.4,
        "focus": 0.5,
        "relax": 0.6,
        "sleep": -0.2,
        "mood": 0.4,
        "balance": 0.7,
        "sustained_focus": 0.5,
        "mood_boost":0.4,
        "clear_head": 0.6,
        "gentle_stimulation": 0.8,
        "jitters": -0.6,
        "crash": -0.5,
        "anxiety": -0.5,
        "insomnia": -0.3,
        "stomach_upset": -0.2,
        "urgancy": 0.2

    },
    "matcha":{
        "energy": 0.6,
        "focus": 0.7,
        "relax": 0.5,
        "sleep": -0.4,
        "mood": 0.5,
        "balance": 0.7,
        "sustained_focus": 0.7,
        "mood_boost":0.5,
        "clear_head": 0.6,
        "gentle_stimulation": 0.6,
        "jitters": -0.5,
        "crash": -0.4,
        "anxiety": -0.4,
        "insomnia": -0.4,
        "stomach_upset": -0.2,
        "urgancy": 0.4
    },
    "black_tea":{
        "energy": 0.5,
        "focus": 0.5,
        "relax": 0.3,
        "sleep": -0.5,
        "mood": 0.4,
        "balance": 0.5,
        "sustained_focus": 0.5,
        "mood_boost":0.4,
        "clear_head": 0.4,
        "gentle_stimulation": 0.5,
        "jitters": -0.4,
        "crash": -0.4,
        "anxiety": -0.3,
        "insomnia": -0.5,
        "stomach_upset": -0.3,
        "urgancy": 0.4
    },
    "yerba_mate":{
        "energy": 0.8,
        "focus": 0.7,
        "relax": 0.2,
        "sleep": -0.7,
        "mood": 0.6,
        "balance": 0.4,
        "sustained_focus": 0.6,
        "mood_boost":0.6,
        "clear_head": 0.6,
        "gentle_stimulation": 0.5,
        "jitters": -0.3,
        "crash": -0.4,
        "anxiety": -0.3,
        "insomnia": -0.6,
        "stomach_upset": -0.3,
        "urgancy": 0.6
    },
    "brewed_coffee":{
        "energy": 0.9,
        "focus": 0.8,
        "relax": -0.2,
        "sleep": -0.9,
        "mood": 0.6,
        "balance": 0.2,
        "sustained_focus": 0.7,
        "mood_boost":0.5,
        "clear_head": 0.5,
        "gentle_stimulation": 0.3,
        "jitters": -0.6,
        "crash": -0.6,
        "anxiety": -0.6,
        "insomnia": -0.8,
        "stomach_upset": -0.4,
        "urgancy": 0.8
    },
    # PLACEHOLDER VALUES BELOW THIS POINT
    "cold_brew":{
        "energy": 0.4,
        "focus": 0.5,
        "relax": 0.6,
        "sleep": -0.2,
        "mood": 0.4,
        "balance": 0.7,
        "sustained_focus": 0.5,
        "mood_boost":0.4,
        "clear_head": 0.6,
        "gentle_stimulation": 0.8,
        "jitters": -0.6,
        "crash": -0.5,
        "anxiety": -0.5,
        "insomnia": -0.3,
        "stomach_upset": -0.2,
        "urgancy": 0.2
    },
    "espresso":{
        "energy": 0.4,
        "focus": 0.5,
        "relax": 0.6,
        "sleep": -0.2,
        "mood": 0.4,
        "balance": 0.7,
        "sustained_focus": 0.5,
        "mood_boost":0.4,
        "clear_head": 0.6,
        "gentle_stimulation": 0.8,
        "jitters": -0.6,
        "crash": -0.5,
        "anxiety": -0.5,
        "insomnia": -0.3,
        "stomach_upset": -0.2,
        "urgancy": 0.2
    },
    "decaf_coffee":{
        "energy": 0.4,
        "focus": 0.5,
        "relax": 0.6,
        "sleep": -0.2,
        "mood": 0.4,
        "balance": 0.7,
        "sustained_focus": 0.5,
        "mood_boost":0.4,
        "clear_head": 0.6,
        "gentle_stimulation": 0.8,
        "jitters": -0.6,
        "crash": -0.5,
        "anxiety": -0.5,
        "insomnia": -0.3,
        "stomach_upset": -0.2,
        "urgancy": 0.2
    },
    "energy_drink":{
        "energy": 0.4,
        "focus": 0.5,
        "relax": 0.6,
        "sleep": -0.2,
        "mood": 0.4,
        "balance": 0.7,
        "sustained_focus": 0.5,
        "mood_boost":0.4,
        "clear_head": 0.6,
        "gentle_stimulation": 0.8,
        "jitters": -0.6,
        "crash": -0.5,
        "anxiety": -0.5,
        "insomnia": -0.3,
        "stomach_upset": -0.2,
        "urgancy": 0.2
    }
}
